name: update-goldhist

on:
  schedule:
    - cron: '30 22 * * 1-5'   # TODO: adjust UTC time
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
      - name: Update data and latest.json
        run: |
          python scripts/update_goldhist.py
      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/Goldhist.csv docs/latest.json
          git commit -m "chore: update Goldhist & latest.json [skip ci]" || echo "No changes"
          git push
