name: update-goldhist

on:
  schedule:
    - cron: '05 4 * * 1-5'   # 06:05 in Berlin during CEST (UTC+2)
    - cron: '05 5 * * 1-5'   # 06:05 in Berlin during CET  (UTC+1)
  workflow_dispatch: {}

permissions:
  contents: write         # needed to push updated files

concurrency:
  group: update-goldhist
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy
          pip install -r requirements.txt

      - name: Run updater
        run: |
          python scripts/update_goldhist.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # only add the files that should change
          git add data/Goldhist.csv docs/latest.json || true

          # commit only when there is a diff
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update Goldhist & latest.json [skip ci]"
            git push
          fi
